{
	"version": 1660581238,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"img/sprite-sheet0.png",
		"img/sprite-sheet1.png",
		"img/sprite-sheet2.png",
		"img/sprite-sheet3.png",
		"img/chara-sheet0.png",
		"img/chara-sheet1.png",
		"img/chara-sheet2.png",
		"img/chara-sheet3.png",
		"img/bkg.png",
		"img/ans.png",
		"img/sprite2-sheet0.png",
		"media/mechanical-keyboard-single-button-presses-9-www.fesliyanstudios.com.m4a",
		"media/techno-loop.ogg",
		"media/a78cf0d31b6ea23.ogg",
		"media/ace-of-base-happy-nation_dj-white-man-remix_-_promodj.com_.ogg",
		"media/без названия.m4a",
		"media/без названия.ogg",
		"media/indie 11-08-2022 04-54.m4a",
		"media/indie 11-08-2022 04-54.ogg",
		"loading-logo.png",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png"
	]
}